server_id: ''
address: "localhost"
port: 6379
password: ""
chat:
  enable: true
  enable-splitting: true
  local-server-chat-radius: 100
  local-chat-format: "&a[L] {prefix}{username}{suffix}: {message}"
  global-chat-format: "&6[G] {prefix}{username}{suffix}: {message}"
  admin-message-color: "&c"
queue:
  ensure-joined-via: true
  connection-timeout: 10
rcon:
  password: '123'
  port: 3999
  whitelist: true,
  whitelisted:
    - '0.0.0.0'

